version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      platforms:
        - "linux/arm64"
    
    container_name: ${COOLIFY_APP_NAME:-remix-app}
    
    environment:
      - GROQ_API_KEY
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      - VITE_LOG_LEVEL
    
    labels:
      coolify.managed: "true"
    
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    
    restart: always