version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    
    container_name: ${COOLIFY_APP_NAME:-remix-app}
    
    environment:
      - GROQ_API_KEY
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      - VITE_LOG_LEVEL
    
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    
    restart: always